"""added lazy dynamic loading for users relation

Revision ID: b116945b3825
Revises: e87e4b8e290c
Create Date: 2016-01-01 14:49:36.558263

"""

# revision identifiers, used by Alembic.
revision = 'b116945b3825'
down_revision = 'e87e4b8e290c'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
