"""empty message

Revision ID: c853c924be99
Revises: 870c69149795
Create Date: 2016-03-21 19:13:46.273640

"""

# revision identifiers, used by Alembic.
revision = 'c853c924be99'
down_revision = '870c69149795'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
