"""updating remote database

Revision ID: fced7ebc5cbe
Revises: c853c924be99
Create Date: 2016-03-21 19:18:41.858421

"""

# revision identifiers, used by Alembic.
revision = 'fced7ebc5cbe'
down_revision = 'c853c924be99'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
